package enums

enum class TareasDomesticasEnum {
    LAVAR_PLATOS,
    LAVAR_ROPA,
    LIMPIAR_CASA,
    HACER_COMPRAS,
    COCINAR,
    LIMPIAR_BANIO,
    LIMPIAR_PATIO,
    LIMPIAR_GARAJE,
    LIMPIAR_VENTANAS,
    LIMPIAR_ESCALERAS,
    LIMPIAR_PISCINA,
    LIMPIAR_JARDIN,
    LIMPIAR_TERRAZA,
    LIMPIAR_COCINA,
    LIMPIAR_SALA,
    LIMPIAR_COMEDOR,
    LIMPIAR_HABITACION,
    LIMPIAR_BODEGA,
}